### ISSUE TITLE
Newline character (\n) is not preserved.

### ISSUE THREAD

**Issue by AchoArnold** [invopop/ctxi18n#10]
When I have a translation template with a newline character, the newline character (`\n`) isn't preserved in the translated output. Instead I get an escaped newline character `\\n`

### Repro Steps.

en.yml
```yml
en:
  temp1: |
    Hello
    World
  temp2: Hello \n\n World
```

main.go

```go
ctx, err := ctxi18n.WithLocale(context.Background(), "en")
if err != nil {
    panic(err)
}

fmt.Print(i18n.T(ctx, "temp2"))
````

### Actual

```
"Hello \\n\\n World"
```

### Expected

```
"Hello \n\n World"
```
