### ISSUE TITLE
BUG: 3 layers of depth seems to not work

### ISSUE THREAD

**Issue by Oudwins** [invopop/ctxi18n#8]
Given the following yaml code:

```yaml
# es.yaml
es:
  serps:
      not_found:
        title: No se han encontrado resultados con los filtros seleccionados.
        subtitle: Por favor, cambie los términos de búsqueda.
```

This doesn't seem to work
```go
	fmt.Printf("%+v", ctxi18n.Get(ES).T("serps.not_found.title"))
```

I might be running an older versión let me try to update
